improved formatting git hook (#1133)

diff --git a/dev/hooks/pre-commit b/dev/hooks/pre-commit
--- a/dev/hooks/pre-commit
+++ b/dev/hooks/pre-commit
@@ -8,6 +8,11 @@ RESULT=$?
 
 # If the result is non-zero (i.e., there were formatting errors), abort the commit
 if [ $RESULT -ne 0 ]; then
-    echo "There are formatting errors. Please run 'cargo +nightly fmt' and fix them before committing."
-    exit 1
+  if [ -z "$(git ls-files --others --modified --exclude-standard)" ]; then
+    echo "There are formatting errors. Running cargo fmt. Please check the formatting changes and add them before committing."
+    cargo +nightly fmt --all
+  else
+    echo "There are formatting errors and un-staged files. Please run 'cargo +nightly fmt --all' to fix the formatting before committing."
+  fi
+   exit 1
 fi
